# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.10-slim

# Set working directory
WORKDIR /app

# Copy necessary files
COPY pyproject.toml .
COPY README.md .
COPY LICENSE .
COPY src ./src
COPY uv.lock .

# Install build system requirements
RUN pip install --upgrade pip && \
    pip install hatchling

# Install project dependencies, ignoring scripts if necessary
RUN pip install .

# Use the installed command from the package entry point
CMD ["emqx-mcp-server"]
